apiVersion: apigateway.aws.upbound.io/v1beta1
kind: RestAPI
metadata:
  name: example-rest-api
spec:
  forProvider:
    region: us-west-2
    description: "Example RestAPI"
    endpointConfiguration:
      types:
        - EDGE
    name: example-rest-api
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Resource
metadata:
  name: example-resource
spec:
  forProvider:
    region: us-west-2
    parentIdRef:
      name: example-rest-api
    restApiIdRef:
      name: example-rest-api
    pathPart: lambda
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Method
metadata:
  name: example-method
spec:
  forProvider:
    region: us-west-2
    apiKeyRequired: false
    authorization: NONE
    httpMethod: GET
    operationName: lambda
    resourceIdRef:
      name: example-resource
    restApiIdRef:
      name: example-rest-api
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Integration
metadata:
  name: example-integration
spec:
  forProvider:
    region: us-west-2
    connectionType: INTERNET
    integrationHttpMethod: GET
    resourceIdRef:
      name: example-resource
    restApiIdRef:
      name: example-rest-api
    type: AWS_PROXY
    uriRef:
      name: crossplane-function-testing-two-haves
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Model
metadata:
  name: example-model
spec:
  forProvider:
    region: us-west-2
    contentType: application/json
    description: "Example Model"
    name: example-model
    restApiIdRef:
      name: example-rest-api
    schema: |
      {}
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Stage
metadata:
  name: example-stage
spec:
  forProvider:
    region: us-west-2
    restApiIdRef:
      name: example-rest-api
    stageName: example-stage
---
apiVersion: apigateway.aws.upbound.io/v1beta1
kind: Deployment
metadata:
  name: example-deployment
spec:
  forProvider:
    region: us-west-2
    restApiIdRef:
      name: example-rest-api
    stageName: example-deployment
