apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: crossplane-bucket-testing
  labels:
    docs.crossplane.io/example: provider-aws
spec:
  forProvider:
    region: us-west-2
  providerConfigRef:
    name: default