apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: example
      name: aws-creds
      key: credentials